import { useEffect, useState } from 'react'
import { AlertTriangle, FlaskConical, Inbox, Loader2 } from 'lucide-react'

export function useAsync(fn, deps) {
  const [s, setS] = useState({ data: null, loading: true, error: null })
  useEffect(() => {
    let live = true
    setS((p) => ({ ...p, loading: true, error: null }))
    Promise.resolve().then(fn).then((data) => live && setS({ data, loading: false, error: null }))
      .catch((error) => live && setS({ data: null, loading: false, error }))
    return () => { live = false }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, deps)
  return s
}

export const Card = ({ title, subtitle, right, children, className = '' }) => (
  <section className={`rounded-xl border border-slate-200 bg-white p-4 shadow-sm dark:border-slate-800 dark:bg-slate-900 ${className}`}>
    {(title || right) && (
      <header className="mb-3 flex items-start justify-between gap-3">
        <div>
          {title && <h3 className="text-sm font-semibold text-slate-900 dark:text-slate-100">{title}</h3>}
          {subtitle && <p className="mt-0.5 text-xs text-slate-500 dark:text-slate-400">{subtitle}</p>}
        </div>
        {right}
      </header>
    )}
    {children}
  </section>
)

const TONES = {
  measured: 'bg-sky-50 text-sky-700 ring-sky-200 dark:bg-sky-950 dark:text-sky-300 dark:ring-sky-900',
  derived: 'bg-violet-50 text-violet-700 ring-violet-200 dark:bg-violet-950 dark:text-violet-300 dark:ring-violet-900',
  predicted: 'bg-amber-50 text-amber-800 ring-amber-200 dark:bg-amber-950 dark:text-amber-300 dark:ring-amber-900',
  good: 'bg-emerald-50 text-emerald-700 ring-emerald-200 dark:bg-emerald-950 dark:text-emerald-300 dark:ring-emerald-900',
  warn: 'bg-amber-50 text-amber-800 ring-amber-200 dark:bg-amber-950 dark:text-amber-300 dark:ring-amber-900',
  bad: 'bg-rose-50 text-rose-700 ring-rose-200 dark:bg-rose-950 dark:text-rose-300 dark:ring-rose-900',
  neutral: 'bg-slate-100 text-slate-600 ring-slate-200 dark:bg-slate-800 dark:text-slate-300 dark:ring-slate-700',
}
export const Badge = ({ tone = 'neutral', children }) => (
  <span className={`inline-flex items-center rounded-full px-2 py-0.5 text-[11px] font-medium ring-1 ring-inset ${TONES[tone]}`}>{children}</span>
)

export const Kpi = ({ label, value, unit, kind, hint, icon: Icon }) => (
  <Card>
    <div className="flex items-center justify-between">
      <span className="text-xs font-medium text-slate-500 dark:text-slate-400">{label}</span>
      {Icon && <Icon className="h-4 w-4 text-slate-400" aria-hidden />}
    </div>
    <div className="mt-2 flex items-baseline gap-1">
      <span className="num text-2xl font-semibold text-slate-900 dark:text-white">{value}</span>
      {unit && <span className="text-xs text-slate-500">{unit}</span>}
    </div>
    <div className="mt-2 flex items-center gap-2">
      {kind && <Badge tone={kind}>{kind}</Badge>}
      {hint && <span className="text-[11px] text-slate-500 dark:text-slate-400">{hint}</span>}
    </div>
  </Card>
)

export const Loading = ({ label = 'Loading…' }) => (
  <div className="flex items-center justify-center gap-2 py-10 text-sm text-slate-500" role="status">
    <Loader2 className="h-4 w-4 animate-spin" /> {label}
  </div>
)
export const ErrorBox = ({ error }) => (
  <div role="alert" className="flex gap-2 rounded-lg border border-rose-200 bg-rose-50 p-3 text-sm text-rose-800 dark:border-rose-900 dark:bg-rose-950 dark:text-rose-200">
    <AlertTriangle className="mt-0.5 h-4 w-4 shrink-0" />
    <div><div className="font-medium">Something went wrong</div><div className="text-xs opacity-90">{error?.message || String(error)}</div></div>
  </div>
)
export const Empty = ({ title, hint }) => (
  <div className="flex flex-col items-center gap-1 py-10 text-center text-slate-500">
    <Inbox className="h-6 w-6" /><div className="text-sm font-medium">{title}</div>{hint && <div className="max-w-md text-xs">{hint}</div>}
  </div>
)
export const Async = ({ state, children, empty }) =>
  state.loading ? <Loading /> : state.error ? <ErrorBox error={state.error} /> : state.data == null ? empty || null : children(state.data)

export const DemoBanner = ({ dataset }) =>
  dataset?.is_demo ? (
    <div className="mb-4 flex items-start gap-2 rounded-lg border border-amber-300 bg-amber-50 px-3 py-2 text-xs text-amber-900 dark:border-amber-800 dark:bg-amber-950 dark:text-amber-200">
      <FlaskConical className="mt-0.5 h-4 w-4 shrink-0" />
      <div><b>Demo / Sample Data.</b> This dataset is <b>synthetic</b>, generated by a simple simulator so the app runs without the NASA download.
        Every number below describes the simulator, not real batteries. Train on real NASA data (see README) for genuine results.</div>
    </div>
  ) : null

export const Field = ({ label, children, hint }) => (
  <label className="block text-xs font-medium text-slate-600 dark:text-slate-300">
    {label}<div className="mt-1">{children}</div>{hint && <span className="mt-1 block font-normal text-slate-500">{hint}</span>}
  </label>
)
const inputCls = 'w-full rounded-md border border-slate-300 bg-white px-2.5 py-1.5 text-sm text-slate-900 dark:border-slate-700 dark:bg-slate-950 dark:text-slate-100'
export const Select = ({ value, onChange, options, ...p }) => (
  <select value={value ?? ''} onChange={(e) => onChange(e.target.value)} className={inputCls} {...p}>
    {options.map((o) => <option key={o.value ?? o} value={o.value ?? o}>{o.label ?? o}</option>)}
  </select>
)
export const NumberInput = ({ value, onChange, ...p }) => (
  <input type="number" value={value ?? ''} onChange={(e) => onChange(e.target.value === '' ? '' : Number(e.target.value))} className={inputCls} {...p} />
)
export const Button = ({ children, ...p }) => (
  <button {...p} className="inline-flex items-center justify-center gap-1.5 rounded-md bg-brand-600 px-3 py-1.5 text-sm font-medium text-white hover:bg-brand-700 disabled:opacity-50">{children}</button>
)

export const fmt = (v, d = 2) => (v == null || Number.isNaN(v) ? '—' : Number(v).toFixed(d))
export const PageTitle = ({ title, subtitle }) => (
  <div className="mb-4"><h1 className="text-xl font-semibold text-slate-900 dark:text-white">{title}</h1>{subtitle && <p className="text-sm text-slate-500 dark:text-slate-400">{subtitle}</p>}</div>
)
